"""LLM calls, with every response cached to disk.

Two reasons the cache is not optional:

* Cost. Every evaluation re-asks the same questions under a new retrieval
  configuration, and the question set itself is generated by a model. Without a
  cache, checking a number again means paying for it again.
* Reproducibility. temperature=0 makes a model *mostly* deterministic, not
  deterministic. Caching on a hash of the exact request is what makes a
  published number reproducible, and what lets a run replay offline.

The cache key covers everything that can change the output -- provider, model,
system prompt, user prompt, temperature, max_tokens, JSON mode -- so editing a
prompt correctly misses the cache instead of silently returning the old answer.
"""

from __future__ import annotations

import hashlib
import json
import os
import random
import threading
import time
from dataclasses import dataclass
from pathlib import Path

from . import config

DEFAULT_MODEL = os.environ.get("LLM_MODEL", "gpt-4o-mini")
DEFAULT_MAX_TOKENS = 600
_RETRIES = 4

# Ask the API not to brotli-compress its responses. The SDK's HTTP stack calls
# `decompress(data, output_buffer_limit=...)` on brotli bindings whose
# `decompress` has no such parameter, so every compressed response dies in the
# decoder before any of our code sees it. Dropping brotli costs a little
# bandwidth on small JSON payloads and removes the dependency on which bindings
# happen to be installed.
_HTTP_HEADERS = {"Accept-Encoding": "gzip, deflate"}

# HTTP statuses where retrying the identical request is reasonable.
_RETRYABLE_STATUS = {408, 409, 425, 429, 500, 502, 503, 504}
_RETRYABLE_NAMES = {
    "APIConnectionError",
    "APITimeoutError",
    "RateLimitError",
    "InternalServerError",
    "ConnectionError",
    "Timeout",
}


def _is_retryable(exc: Exception) -> bool:
    """A bad key or a malformed request fails identically every time, so only
    transient failures are retried -- anything else surfaces immediately with
    its own traceback instead of after seconds of backoff."""
    status = getattr(exc, "status_code", None)
    if isinstance(status, int):
        return status in _RETRYABLE_STATUS
    return type(exc).__name__ in _RETRYABLE_NAMES


@dataclass
class LLMResponse:
    text: str
    cached: bool
    model: str
    input_tokens: int = 0
    output_tokens: int = 0
    latency_s: float = 0.0


@dataclass
class UsageStats:
    calls: int = 0  # requests actually sent to the provider
    cache_hits: int = 0
    input_tokens: int = 0
    output_tokens: int = 0


def _provider_for(model: str) -> str:
    if model.startswith("claude"):
        return "anthropic"
    if model.startswith(("gpt", "o1", "o3", "o4")):
        return "openai"
    raise ValueError(f"cannot infer provider for model {model!r}; set LLM_PROVIDER explicitly")


class LLMClient:
    """Thin wrapper over the provider SDKs, with a content-addressed disk cache.

    Not a framework: the prompt that goes out is built in this repo and is
    readable verbatim in the cache file on disk.
    """

    def __init__(
        self,
        model: str = DEFAULT_MODEL,
        provider: str | None = None,
        cache_dir: Path | None = None,
        offline: bool | None = None,
    ) -> None:
        self.model = model
        self.provider = provider or os.environ.get("LLM_PROVIDER") or _provider_for(model)
        self.cache_dir = cache_dir or config.CACHE_DIR
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        # Offline mode fails on a cache miss instead of spending money -- how a
        # published number is shown to reproduce rather than be re-rolled.
        self.offline = offline if offline is not None else os.environ.get("LLM_OFFLINE") == "1"
        self.usage = UsageStats()
        self._client = None  # created lazily so cached runs need no API key
        self._lock = threading.Lock()  # batch scripts call this from a thread pool

    # ------------------------------------------------------------------ cache

    def _key(self, **request: object) -> str:
        payload = json.dumps(
            {"provider": self.provider, "model": self.model, **request},
            sort_keys=True,
            ensure_ascii=False,
        )
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()

    def _cache_path(self, key: str) -> Path:
        # Sharded: a flat directory of thousands of files is slow on Windows.
        return self.cache_dir / key[:2] / f"{key}.json"

    def _read_cache(self, key: str) -> dict | None:
        path = self._cache_path(key)
        if not path.exists():
            return None
        try:
            with path.open(encoding="utf-8") as fh:
                return json.load(fh)
        except (json.JSONDecodeError, OSError):
            return None  # a truncated entry from an interrupted run is re-fetched

    def _write_cache(self, key: str, record: dict) -> None:
        path = self._cache_path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(".tmp")
        with tmp.open("w", encoding="utf-8") as fh:
            json.dump(record, fh, ensure_ascii=False, indent=2)
        tmp.replace(path)  # atomic, so Ctrl-C cannot leave a half-written entry

    # ----------------------------------------------------------------- calls

    def complete(
        self,
        user: str,
        system: str = "",
        temperature: float = 0.0,
        max_tokens: int = DEFAULT_MAX_TOKENS,
        json_mode: bool = False,
        cache_salt: str = "",
    ) -> LLMResponse:
        """Send one request (or serve it from cache) and return the raw text.

        `json_mode` asks the provider to return a single JSON object (OpenAI's
        `response_format`); it is part of the cache key because it changes the
        output. `cache_salt` separates requests that are identical but meant to
        differ, such as several samples at temperature > 0.
        """
        key = self._key(
            system=system, user=user, temperature=temperature,
            max_tokens=max_tokens, json_mode=json_mode, cache_salt=cache_salt,
        )
        hit = self._read_cache(key)
        if hit is not None:
            with self._lock:
                self.usage.cache_hits += 1
            return LLMResponse(
                text=hit["text"],
                cached=True,
                model=hit.get("model", self.model),
                input_tokens=hit.get("input_tokens", 0),
                output_tokens=hit.get("output_tokens", 0),
                latency_s=hit.get("latency_s", 0.0),
            )

        if self.offline:
            raise RuntimeError(f"cache miss in offline mode (key {key[:12]}); unset LLM_OFFLINE")

        started = time.monotonic()
        text, in_tok, out_tok = self._call_with_retries(system, user, temperature, max_tokens, json_mode)
        latency = time.monotonic() - started

        with self._lock:
            self.usage.calls += 1
            self.usage.input_tokens += in_tok
            self.usage.output_tokens += out_tok

        self._write_cache(key, {
            "provider": self.provider, "model": self.model, "system": system,
            "user": user, "temperature": temperature, "max_tokens": max_tokens,
            "json_mode": json_mode, "cache_salt": cache_salt, "text": text,
            "input_tokens": in_tok, "output_tokens": out_tok,
            "latency_s": round(latency, 3),
        })
        return LLMResponse(text=text, cached=False, model=self.model,
                           input_tokens=in_tok, output_tokens=out_tok, latency_s=latency)

    def _call_with_retries(self, system: str, user: str, temperature: float,
                           max_tokens: int, json_mode: bool) -> tuple[str, int, int]:
        last: Exception | None = None
        for attempt in range(_RETRIES):
            try:
                if self.provider == "anthropic":
                    return self._call_anthropic(system, user, temperature, max_tokens)
                return self._call_openai(system, user, temperature, max_tokens, json_mode)
            except Exception as exc:
                last = exc
                if not _is_retryable(exc):
                    raise
                if attempt == _RETRIES - 1:
                    break
                # Backoff with jitter, so a batch does not retry in lockstep.
                time.sleep((2**attempt) + random.random())
        raise RuntimeError(f"LLM call failed after {_RETRIES} attempts: {last}") from last

    def _call_anthropic(self, system: str, user: str, temperature: float,
                        max_tokens: int) -> tuple[str, int, int]:
        with self._lock:
            if self._client is None:
                import anthropic

                self._client = anthropic.Anthropic(default_headers=_HTTP_HEADERS)
        msg = self._client.messages.create(
            model=self.model, max_tokens=max_tokens, temperature=temperature,
            system=system or None, messages=[{"role": "user", "content": user}],
        )
        text = "".join(block.text for block in msg.content if block.type == "text")
        return text, msg.usage.input_tokens, msg.usage.output_tokens

    def _call_openai(self, system: str, user: str, temperature: float,
                     max_tokens: int, json_mode: bool) -> tuple[str, int, int]:
        with self._lock:
            if self._client is None:
                import openai

                self._client = openai.OpenAI(default_headers=_HTTP_HEADERS)
        messages = [{"role": "system", "content": system}] if system else []
        messages.append({"role": "user", "content": user})
        extra = {"response_format": {"type": "json_object"}} if json_mode else {}
        resp = self._client.chat.completions.create(
            model=self.model, messages=messages, temperature=temperature,
            max_tokens=max_tokens, **extra,
        )
        usage = resp.usage
        return (resp.choices[0].message.content or "",
                getattr(usage, "prompt_tokens", 0), getattr(usage, "completion_tokens", 0))
